Tutorials/06_Creating FIXME Issues from Code Comments.md

There was some text missing from the FIXME tutorial, so I added it to the respective Markdown file.

Added missing text.

---

main.gms

Enabled the GAMS execution profile to identify bottlenecks in the OPEN-PROM code. This has two main features:
* Creating a profile summary with the most "expensive" statements, sorted by execution time
* Displaying information about every individual statement in the .lst file

Enabled the GAMS execution profile

---

reportData.R

Added `MENA-EDS` data as reference to the `OPEN-PROM` validation script.

Added MENA-EDS reference data

---

MENA-PROM mapping - mena_prom_mapping.csv
reportData.R

fix function reportData

---

reportData.R
reportOutput.R

add function reportOutput

---

sets.gms

Test Commit Process

---

reportPrice.R

fix units reportPrice

---

reportFinalEnergy.R

change variable names at function reportFinalEnergy
use readEnerdata instead of calcIFuelCons
add IEA projections
add IEA WB

reportFinalEnergy

---

reportFinalEnergy.R

add IEA total to reporting

---

main.gms

* GDX files are reduced to approximately 5% of their original size
* Compressed GDX files can be read by `gdx::readGDX()` without any issues

Enabled GDX Compression

---

reportEmissions.R
reportFinalEnergy.R

mean consumption of Navigate models to reporting
CO2, NOx, CH4 from Navigate to reporting

Consumption Navigate , CO2 NOx CH4 Navigate to reporting

---

.vscode/tasks.json
start.R

Added debugging mode and changed timestamp format.
* Debugging mode runs the model with the default settings of `main.gms`, without creating a new folder or uploading to Google Drive. For custom runs, you can configure the `DevMode` and `GenerateInput` settings.
* The new timestamp format is YYYY-MM-DD_HH-MM-SS.

Debugging Mode and Timestamp Format

---

reportFinalEnergy.R

Consumption diff navigate model

---

reportFinalEnergy.R

Add final energy total, by fuel, by sector navigate to reporting

Add final energy total, by fuel, by sector navigate to reporting

---

.gitignore
Tutorials/03_Running OPEN‐PROM.md
config.json
config.template.json
start.R

* Added some code to handle the google drive upload failure

Google Drive fallback

---

reportFinalEnergy.R

Fix reporting issues IEA, ENERDATA, OPEN-PROM
Add final energy variable navigate to reporting
Report IAMC

Add final energy variable navigate to reporting

---

config.template.json
input.gms
start.R

* Added model run description parameter to `config.json` that gets passed to `metadata.json`
* Added the iElcNetImpShare dataset to `input.gms`
* Also updated the Github action dataset on Google Drive, based on the latest `mrprom` (version 1.10.4)

Added description to metadata and iElcNetImpShare

---

reportFinalEnergy.R
reportOutput.R
reportSE.R

Add secondary energy electricity, add fuels to final energy

Add secondary energy electricity, add fuels to final energy

---

reportEmissions.R
reportFinalEnergy.R
reportOutput.R
reportPE.R

add Primay Energy to Reporting

add Primay Energy to Reporting

---

main.gms
start.R

* In case the model runs path is invalid, script execution will stop

Removed uploadToGDrive() function and created syncRun()

---

equations.gms

correct equation formulation to follow MENA-EDS

---

reportEmissions.R
reportFinalEnergy.R

1.5C and 2C and Cumulated co2 emissions to fullVALIDATION

add Cumulated co2 emissions to open-prom

---

scripts/compare_targets_calib.R

add function compare_targets_calib

add function compare_targets_calib

---

reportEmissions.R
reportGDP.R
reportOutput.R
reportPOP.R

add GDP and POP to reporting

---

preloop.gms

To have a more realistic starting point

VRenTechMatMult level set to 1 from 0.1

---

declarations.gms
equations.gms
preloop.gms

QRenTechMatMultExpr for easier monitoring of expression in exp of QRenTechMatMult

---

reportOutput.R
reportPriceCarbon.R

add carbon price to reporting

---

reportCapacityElectricity.R
reportEmissions.R
reportFinalEnergy.R
reportOutput.R
reportPE.R
reportPrice.R
reportSE.R
scripts/compare_targets_calib.R

use csv indstead of toolreadSets

---

reportFinalEnergy.R

change name of fuels in reporting and ad ENERDATA variables in calcIFuelCons

---

reportEmissions.R

EMISSIONS|CO2|ENERGY = EMISSIONS|CO2
add_emissions_CO2_demand

add_emissions_CO2_demand

---

reportSE.R

add sectors of SE to reporting

---

reportCapacityElectricity.R
reportEmissions.R
reportFinalEnergy.R
reportGDP.R
reportOutput.R
reportPE.R
reportPOP.R
reportPrice.R
reportPriceCarbon.R
reportSE.R

calcul_mbind

---

reportSE.R

add plots to reportSE

---

reportCapacityElectricity.R

add plots Capacity Electricity

---

reportFinalEnergy.R

add FE plots

---

tutorials/06_Regionalization in OPEN-PROM.md

Regionalization fixed in the tutorial

Regionalization fixed in tutotial 6

---

reportEmissions.R

geom_area emissions graphs

---

reportEmissions.R

fix_regions_report_Emissions

---

.github/workflows/deploy_docs.yml

New workflow to update OPEN-PROM documentation

---

core/sets.gms
core/solve.gms

solver attempts counter was not starting from 1

fix solver attempts issue
